# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
