# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20160407_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Both'), (3, 'None')], default=2),
        ),
    ]
