# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
