# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160408_1410'),
        ('item', '0007_rating_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemflags', to='item.Item')),
            ],
        ),
    ]
